### ISSUE TITLE
一直显示彩虹括号不兼容；

### ISSUE THREAD

**Issue by Cazaea** [getActivity/StudioPlugins#1]

**Comment by getActivity** [comment]
[https://github.com/izhangzhihao/intellij-rainbow-brackets](https://github.com/izhangzhihao/intellij-rainbow-brackets)

**Comment by getActivity** [comment]
请移步至作者反馈

**Comment by Cazaea** [comment]
我的意思，你们那边好用吗？是否在用？
还是说只整理了文章，没有实际使用，不知道这个问题；

**Comment by Cazaea** [comment]
我已经解决了问题，谢谢。

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/92383176-6ef56b80-f140-11ea-8960-d91a0c8311f9.png)

**Comment by getActivity** [comment]
所有的插件我都有经过测试，还有文章里面的介绍都是我一个个字手敲的，没有复制或者转载
