### ISSUE TITLE
AndroidDrawablePreview doesn't work in Android Studio Hedgehog | 2023.1.1

### ISSUE THREAD

**Issue by MALTF** [getActivity/StudioPlugins#3]
[plugins/AndroidDrawablePreview-1.1.6-fix.zip](https://github.com/getActivity/StudioPlugins/blob/master/plugins/AndroidDrawablePreview-1.1.6-fix.zip)
It doesn't work in Android Studio Hedgehog | 2023.1.1.
![(version '1 1 6-fix')](https://github.com/getActivity/StudioPlugins/assets/15863058/7d9044fc-e5f3-4e4c-9750-ebbb29a8432e)

Android Studio Hedgehog | 2023.1.1
Build #AI-231.9392.1.2311.11076708, built on November 10, 2023
Runtime version: 17.0.7+0-17.0.7b1000.6-10550314 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.1.2

Non-Bundled Plugins:
    com.mistamek.drawablepreview.drawable-preview (1.1.6)

**Comment by getActivity** [comment]
@MALTF 小伙子，这种问题只能找插件的作者解决了

**Comment by MALTF** [comment]
好的
